# Copy this file to secrets.toml and fill in your actual values
supabase_url = "YOUR_SUPABASE_PROJECT_URL"  # e.g., "https://xxxxxxxxxxxxxxxxxxxx.supabase.co"
supabase_key = "YOUR_SUPABASE_ANON_KEY"     # e.g., "eyJxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
